Creating CPF structure
brazanation/go-documents pull request #1
Opened 2018-09-28 20:17 UTC by henriqueholanda

On this change I'm implementing the CPF structure, with validation and formatter.

2018-09-28 22:16 UTC, tonicospinelli requested changes

2018-09-28 22:16 UTC, tonicospinelli commented on brdocument/document.go
> +	}
you could use [strings.Trim](https://golang.org/pkg/strings/#Trim) instead makes it by hand

2018-09-28 22:16 UTC, tonicospinelli commented on brdocument/cpf.go
> +)
when add other document it will conflict with other constant, so I suggest type it as a Cpf

2018-09-28 22:16 UTC, tonicospinelli commented on brdocument/document.go
> +	return baseDocument
you could use `strings.Trim` instead makes it by hand

2018-12-14 22:42 UTC, henriqueholanda commented
I opened a new PR with these changes. So I'll close this one.

2018-12-14 22:42 UTC, closed without merging